- hosts: servers_ubuntu
  become: true
  become_user: root
  tasks:
  - name: Update the apt package index
    apt:
      update_cache: yes
    ignore_errors: true

  - name: Install Docker packages
    apt:
      name: docker.io
      state: present
    ignore_errors: true

  - name: Install Docker-compose
    apt:
      name: docker-compose
      state: present
    ignore_errors: true

  - name: Start and enable Docker
    service:
      name: docker
      state: started
      enabled: yes
    ignore_errors: true