- hosts: ubuntu_d0_demo1
  become: true
  become_user: root
  vars:
    node_numbers:
      - "dev1"
      - "dev2"
      - "dev3"
      - "dev4"
      - "dev5"
      - "demo"
      - "prod"
      - "stage"
  tasks:

  # - name: Set_permissions1
  #   command: "chmod 775 /server/{{ inventory_hostname }}/{{ item }}/config/docker-compose.yml"
  #   loop: "{{ node_numbers }}"
  #   become: yes

  # - name: Set_permissions2
  #   command: "chmod 775 /server/{{ inventory_hostname }}/{{ item }}/config/php/8.2/Dockerfile"
  #   loop: "{{ node_numbers }}"
  #   become: yes

  # - name: Set_permissions3
  #   command: "chmod 775 /server/{{ inventory_hostname }}/{{ item }}/config/php/7.4/Dockerfile"
  #   loop: "{{ node_numbers }}"
  #   become: yes

  # - name: Replace string in file
  #   ansible.builtin.replace:
  #     path: "/server/{{ inventory_hostname }}/{{ item }}/config/docker-compose.yml"
  #     regexp: '7.4.33'
  #     replace: '7.4'
  #   loop: "{{ node_numbers }}"
  #   become: true

  # - name: Copy to serv
  #   copy:
  #     src: /root/ansible/upd_packs.sh
  #     dest: /server/{{ inventory_hostname }}/{{ item }}/config/php/upd_packs.sh
  #     owner: "{{ item }}-{{ inventory_hostname }}"
  #     group: "{{ item }}-{{ inventory_hostname }}"
  #     # remote_src: no
  #     # mode: 0644
  #     mode: 755
  #   become: true
  #   loop: "{{ node_numbers }}"

  # - name: Обновление списка пакетов
  #   apt:
  #     update_cache: yes

  # - name: Установка Python 3 на сервер
  #   apt:
  #     name: python3
  #     state: present 
  #   become: yes
    
  # - name: Переопределить интерпретатор Python
  #   set_fact:
  #     ansible_python_interpreter: /usr/bin/python3
      
  # - name: Del folder
  #   file:
  #     path: /home/ubuntu/LAMP/data/
  #     state: absent

  #  - name: Del image1
  #    command: docker image rm image_id_1 -f
  #    ignore_errors: true

  #  - name: Del image2
  #    command: docker image rm image_id_2 -f
  #    ignore_errors: true

    # - name: Stop dockcomp
    #   command: docker-compose down
    #   args:
    #     chdir: ./LAMP

    # - name: Del dockcomp
    #   command: docker rm container_name -f
    #   ignore_errors: true